#!/bin/sh

# ==============================================================================
# OpenWrt Initialization Script  (Side-arm-Gateway)
# ==============================================================================
#
# x86-64
#
# lan 网段:192.168.60.0/24

# ------------------------------------------------------------------------------
# 1. 基础系统设置 (System & Password)
# ------------------------------------------------------------------------------

# 设置主机名
uci set system.@system[0].hostname='Side-arm-Gateway'

# 修改时区
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'

# 设置 LuCI 语言为简体中文
uci set luci.main.lang='zh_cn'

# 修改系统默认密码为 88888888 (SSH 和 Web 界面共享)
# 进入系统必须再次更改密码
sed -i 's|^root:[^:]*:|root:$5$5qZazM6.4xXyh7rc$rutUGbdEV7NQRuf1UyMCFe9ainSxqYIoUqIWSxvuPJA:|' /etc/shadow


# ------------------------------------------------------------------------------
# 2. 服务配置 (Services)
# ------------------------------------------------------------------------------

# 启用 KMS 服务器
uci set vlmcsd.config.enabled='1'
uci set vlmcsd.config.auto_activate='1'
uci -q del vlmcsd.config.internet_access

# 启用 VnStat 流量监控 (监听 br-lan)
uci -q delete vnstat.@vnstat[0]
uci add vnstat vnstat
uci add_list vnstat.@vnstat[-1].interface='br-lan'

# 强制 HTTPS
uci set uhttpd.main.redirect_https='1'


# ------------------------------------------------------------------------------
# 3. 网络接口配置 (Network)
# ------------------------------------------------------------------------------

# 删除默认的 WAN 接口和 WAN6 接口
uci -q delete network.wan
uci -q delete network.wan6

# 配置 LAN 为单臂模式 (Static IP - IPv4)
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.60.2'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.60.1'

# 设置 DNS (使用 add_list 支持列表格式)
uci -q delete network.lan.dns
uci add_list network.lan.dns='192.168.60.1'

# 禁用多路径路由 (Multipath)
uci set network.lan.multipath='off'

# 禁用 LAN 接口的自带 IPv6 属性 (由独立的 lan6 接口接管)
uci set network.lan.ipv6='0'
uci set network.lan.delegate='0'

# ================= 添加 lan6 接口 (DHCPv6 Client) =================
uci set network.lan6='interface'
uci set network.lan6.proto='dhcpv6'
uci set network.lan6.device='br-lan'
uci set network.lan6.reqaddress='try'
uci set network.lan6.reqprefix='auto'
# ========================================================================

# 添加 Tailscale 网段路由 (指向 VM 1014)
uci add network route
uci set network.@route[-1].interface='lan'
uci set network.@route[-1].target='100.64.0.0'
uci set network.@route[-1].netmask='255.192.0.0'
uci set network.@route[-1].gateway='192.168.60.14'
uci set network.@route[-1].comment='Route to Tailscale Subnet'


# ------------------------------------------------------------------------------
# 4. DHCP 与 DNS 配置 (DHCP)
# ------------------------------------------------------------------------------

# 旁路网关深度禁用 DHCP 服务
uci set dhcp.lan.ignore='1'
uci set dhcp.lan.dhcpv4='disabled'

# 彻底清理 IPv6 的路由通告(RA)等相关配置
uci -q delete dhcp.lan.ra
uci -q delete dhcp.lan.ra_slaac
uci -q delete dhcp.lan.ra_flags
uci -q delete dhcp.lan.dhcpv6

# 停止并禁用 odhcpd 服务
/etc/init.d/odhcpd disable


# ------------------------------------------------------------------------------
# 5. 防火墙深度配置 (Firewall - Critical for Side-arm)
# ------------------------------------------------------------------------------

# --- A. 修改默认策略 ---
# 开启 软件流量卸载 (Software Flow Offloading)
uci set firewall.@defaults[0].flow_offloading='1'
# 关闭 SYN-flood 防御 (旁路模式下避免非对称路由导致的丢包)
uci set firewall.@defaults[0].syn_flood='0'
# 默认策略全放行 (内网环境信任)
uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'

# --- B. 锁定并配置 LAN 区域 ---
lan_zone_idx=$(uci show firewall | grep ".name='lan'" | cut -d'.' -f2 | head -1)

if [ -n "$lan_zone_idx" ]; then
    # 开启 IP 动态伪装 (NAT/Masquerade) - 解决旁路回程路由问题
    uci set firewall.$lan_zone_idx.masq='1'
    # 开启 IPv6 动态伪装
    uci set firewall.$lan_zone_idx.masq6='1'
    # 开启 TCP MSS 钳制 (同时对 IPv4/IPv6 生效) - 防止 PMTU 黑洞
    uci set firewall.$lan_zone_idx.mtu_fix='1'
    
    # === 将 lan6 接口也加入到 lan 区域 ===
    # 先删除原有的单字符串配置，改用标准 add_list 包含 lan 和 lan6
    uci -q delete firewall.$lan_zone_idx.network
    uci add_list firewall.$lan_zone_idx.network='lan'
    uci add_list firewall.$lan_zone_idx.network='lan6'
else
    # 如果找不到 lan 区域，强制创建一个
    uci add firewall zone
    uci set firewall.@zone[-1].name='lan'
    uci set firewall.@zone[-1].input='ACCEPT'
    uci set firewall.@zone[-1].output='ACCEPT'
    uci set firewall.@zone[-1].forward='ACCEPT'
    uci set firewall.@zone[-1].masq='1'
    uci set firewall.@zone[-1].masq6='1'
    uci set firewall.@zone[-1].mtu_fix='1'
    uci add_list firewall.@zone[-1].network='lan'
    uci add_list firewall.@zone[-1].network='lan6'
fi


# --- C. 清理 WAN 区域及相关规则 ---
# 这是一个循环清理脚本，删除所有与 wan 相关的区域和转发规则
# 这样比指定删除 cfg03dc81 更安全，因为 cfg ID 会变

# 1. 删除所有 name='wan' 的 zone
uci show firewall | grep "@zone.*.name='wan'" | cut -d'.' -f2 | sort -r | while read -r section_id; do
    uci delete firewall.$section_id
done

# 2. 删除所有 src='wan' 或 dest='wan' 的 forwarding 规则
uci show firewall | grep -E "@forwarding.*.(src|dest)='wan'" | cut -d'.' -f2 | sort -r | uniq | while read -r section_id; do
    uci -q delete firewall.$section_id
done

# ------------------------------------------------------------------------------
# 6. 系统内核参数调整 (Sysctl)
# ------------------------------------------------------------------------------

# === 强制 br-lan 接口接受 IPv6 RA，即使开启了转发 ===
cat >> /etc/sysctl.conf <<EOF

# 强制 br-lan 接口接受 IPv6 RA，即使开启了转发
# 0=拒绝, 1=转发关闭时接受, 2=总是接受
net.ipv6.conf.br-lan.accept_ra=2
net.ipv6.conf.all.accept_ra=2
net.ipv6.conf.default.accept_ra=2
EOF


# ------------------------------------------------------------------------------
# 7. 应用更改 (Apply)
# ------------------------------------------------------------------------------

uci commit system
uci commit luci
uci commit network
uci commit dhcp
uci commit firewall
uci commit uhttpd
uci commit vlmcsd
uci commit vnstat

# 在 uci-defaults 环境中，sysctl -p 有时因为早期启动阶段文件系统未就绪会报错，
# 其实上面写入 /etc/sysctl.conf 即可，系统后续启动自会加载。为安全起见加上 -q (或丢弃输出)
sysctl -p >/dev/null 2>&1

# 脚本结束
exit 0