name: Gitea Build OpenWrt Source Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: 自定义软件源结果检查
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 使用本地的 nexus3 的 apt 代理 , Ubuntu 24.04 (noble)
          cat <<EOF | sudo tee /etc/apt/sources.list
          deb https://nexus.yra.cc/repository/ubuntu-noble-proxy/ noble main restricted universe multiverse
          deb https://nexus.yra.cc/repository/ubuntu-noble-proxy/ noble-updates main restricted universe multiverse
          deb https://nexus.yra.cc/repository/ubuntu-noble-proxy/ noble-backports main restricted universe multiverse
          deb https://nexus.yra.cc/repository/ubuntu-noble-security-proxy/ noble-security main restricted universe multiverse
          EOF

          echo '检查自定义软件源的结果:'
          echo '/etc/apt/sources.list里的内容:'
          cat /etc/apt/sources.list || true

          echo '软件源是DEB822 格式吗?'
          ls -lhR /etc/apt/sources.list.d/ || true

          echo '如果软件源是DEB822 格式,尝试展示内容:'
          cat /etc/apt/sources.list.d/ubuntu.sources || true


          ping git.openwrt.org  -c 4

